#syntax=docker/dockerfile:1

FROM golang:1.16-alpine

WORKDIR /app

# Building
# COPY go.mod ./
# COPY go.sum ./
# RUN go mod download
# COPY *.go ./
# RUN go build -o /out
# CMD ["/out"]

# Dev
CMD [ "go", "run", "main.go" ]
