export { MainCanvas } from './Three/MainCanvas'
export { Navbar } from './Navbar'
export { Hero } from './Home/Hero'
export { About } from './Home/About'
export { Heading } from './Heading'
export { WorkSelector } from './WorkSelector'
export { WorkInfoBox } from './WorkInfoBox' 
